version: '3'
volumes:
  opt-splunk-etc:
  opt-splunk-var:

services:
  helloworld:
    build:
      context: .
      dockerfile: Dockerfile    
    depends_on:
      - splunkworld

  splunkworld: 
    hostname: splunkworld
    build: 
      context: .
      dockerfile: Dockerfile_splunk
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_ADD: tcp 1514
    volumes:
      - opt-splunk-etc:/opt/splunk/etc
      - opt-splunk-var:/opt/splunk/var
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"
    expose:
       - "8000"
       - "8088"
 