version: '3'

services:
  helloworld:
    build:
      context: .
      dockerfile: Dockerfile    
    depends_on:
      - nginxworld

  nginxworld: 
    build: 
      context: .
      dockerfile: Dockerfile_nginx
    ports:
       - "32770:80"
  
  splunkworld:
    build:
      context: .
      dockerfile: Dockerfile_splunk  
    
    environment:
        SPLUNK_START_ARGS: --accept-license  --answer-yes
        SPLUNK_ENABLE_LISTEN: 9997
        SPLUNK_ADD: tcp 1514
    ports:
        - "8000:8000"
        - "9997:9997"
        - "8088:8088"
        - "1514:1514"
    